### ISSUE TITLE
Varsling og digital postkasse ved direkteflyt

### ISSUE THREAD

**Issue by anderslysne** [digipost/signering-docs#34]
Hei! Dette er mer et spørmsål enn et issue, men jeg vet ikke hvor jeg ellers skal spørre om dette.

 Vi har en applikasjon som benytter seg av direkte flyt, og dokumentasjonen oppleves som litt uklar når det gjelder varslinger og brukernes digitale postkasse. 

1. Ved direkteflyt, vil det bli det sendt ut varslinger rundt signeringsoppdraget til brukere eller må dette håndteres av oss? 

2. Dokumentasjonen sier at en bruker vil få mulighet til å opprette en digital postkasse og automatisk få tilsendt det signerte dokumentet dit etter at signeringsporsessen er fullført. Gjelder dette kun portalflyt, eller både portal- og direkteflyt?

3. Dersom en bruker allerede har opprettet en digital postkasse tidligere, blir det ferdig signerte dokumentet sendt til brukerens digitale postkasse når signeringsoppdraget er fullført? Gjelder dette for både portal- og direkteflyt?
 
Kan legge til at signeringsoppdraget vårt inkluderer 2 brukere.

**Comment by simenstoa** [comment]
Hei,

Beklager sent svar herfra. Håper det hjelper likevel.

1: I direkteflyt blir brukeren sendt direkte fra deres system, utfører signering, og til slutt sendt tilbake til deres system, så her er det ingen varsling som skjer av oss.

2 og 3: Undertegner vil få tilbud om å opprette digital postkasse for begge flytene når signeringsoppdraget er fullført (undertegner må opprette postkassen innen 7 dager for å få tilsendt det signerte dokumentet). Hvis undertegner allerede digital postkasse blir dokumentet sendt dit. Dette gjelder bare hvis undertegner er adressert på fødselsnummer. Unntaket er hvis undertegner signerer på vegne av en bedrift/virksomhet, da vil ikke det signerte dokumentet sendes til undertegners private postkasse.
